# Generated by Django 2.1.5 on 2019-01-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userInput',
            field=models.TextField(max_length=300),
        ),
    ]
