# Generated by Django 2.1.5 on 2019-01-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userInput',
            new_name='password',
        ),
    ]
